### ISSUE TITLE
skaffold dev causes segmentation violation with replicas>1

### ISSUE THREAD

**Issue by danielllek** [GoogleContainerTools/skaffold#1268]
`skaffold dev` tries to forward traffic from 0.0.0.0:8080 to multiple pods.
In reality forwards traffic to one pod and dies from time to time with SIGSEGV.

### Expected behavior
Pick only one pod and don't cause segmentation fault.

### Actual behavior
`skaffold dev` tries to forward traffic from 0.0.0.0:8080 to multiple pods (which is not possible without some load balancing)
In reality forwards traffic to one pod and dies from time to time with SIGSEGV.

### Information
- Skaffold version: v0.17.0
- Operating system: Ubuntu 18.04.1 LTS
- Contents of skaffold.yaml:
```yaml
apiVersion: skaffold/v1alpha5
kind: Config
build:
  artifacts:
  - image: ...image...
deploy:
  helm:
    releases:
    - name: node-web-app-helm
      chartPath: helm
      namespace: default
      values:
        image: ...image...
```

```
$ grep replica -r .
./helm/values.yaml:replicas: 4
./helm/templates/k8s-deployment.yaml:  replicas: {{.Values.replicas}}
```

### Steps to reproduce the behavior

1. configure kubectl to some kubernetes cluster (I wasn't using minikube!)
2. run `skaffold dev`
3. leave it running for some time, make changes in your app

it doesn't happen every time, sometimes needs few minutes, sometimes longer, sometimes with just one change, sometimes multiple changes.

log:
```
Watching for changes every 1s...
Port Forwarding node-web-app-565bffbb4-c647l 8080 -> 8080
[node-web-app-565bffbb4-c647l node-web-app] 
[node-web-app-565bffbb4-c647l node-web-app] > docker_web_app@1.0.0 start /usr/src/app
[node-web-app-565bffbb4-c647l node-web-app] > node app.js
[node-web-app-565bffbb4-c647l node-web-app] 
[node-web-app-565bffbb4-c647l node-web-app] Running on http://0.0.0.0:8080
Port Forwarding node-web-app-565bffbb4-q24f8 8080 -> 8080
[node-web-app-565bffbb4-q24f8 node-web-app] 
[node-web-app-565bffbb4-q24f8 node-web-app] > docker_web_app@1.0.0 start /usr/src/app
[node-web-app-565bffbb4-q24f8 node-web-app] > node app.js
[node-web-app-565bffbb4-q24f8 node-web-app] 
[node-web-app-565bffbb4-q24f8 node-web-app] Running on http://0.0.0.0:8080
Port Forwarding node-web-app-565bffbb4-q7k5m 8080 -> 8080
[node-web-app-565bffbb4-q7k5m node-web-app] 
[node-web-app-565bffbb4-q7k5m node-web-app] > docker_web_app@1.0.0 start /usr/src/app
[node-web-app-565bffbb4-q7k5m node-web-app] > node app.js
[node-web-app-565bffbb4-q7k5m node-web-app] 
[node-web-app-565bffbb4-q7k5m node-web-app] Running on http://0.0.0.0:8080
Port Forwarding node-web-app-565bffbb4-2gj5m 8080 -> 8080
[node-web-app-565bffbb4-2gj5m node-web-app] 
[node-web-app-565bffbb4-2gj5m node-web-app] > docker_web_app@1.0.0 start /usr/src/app
[node-web-app-565bffbb4-2gj5m node-web-app] > node app.js
[node-web-app-565bffbb4-2gj5m node-web-app] 
[node-web-app-565bffbb4-2gj5m node-web-app] Running on http://0.0.0.0:8080
Port Forwarding node-web-app-565bffbb4-q7k5m 8080 -> 8080
Port Forwarding node-web-app-565bffbb4-2gj5m 8080 -> 8080
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4960be]

goroutine 256 [running]:
os.(*Process).signal(0x0, 0x164bbc0, 0x1634588, 0x0, 0x0)
	/usr/local/go/src/os/exec_unix.go:56 +0x2e
os.(*Process).Signal(0x0, 0x164bbc0, 0x1634588, 0x1, 0x1)
	/usr/local/go/src/os/exec.go:129 +0x3f
github.com/GoogleContainerTools/skaffold/pkg/skaffold/kubernetes.(*kubectlForwarder).Stop(0x1fa5238, 0xc420208080, 0xc42079ebe8, 0x1350280)
	/go/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/kubernetes/port_forward.go:92 +0xae
github.com/GoogleContainerTools/skaffold/pkg/skaffold/kubernetes.(*PortForwarder).portForwardPod(0xc4200824c0, 0xc4201f5500, 0x431c28, 0x431c28)
	/go/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/kubernetes/port_forward.go:191 +0x77e
github.com/GoogleContainerTools/skaffold/pkg/skaffold/kubernetes.(*PortForwarder).Start.func1.1(0xc4200824c0, 0xc4201f5500)
	/go/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/kubernetes/port_forward.go:152 +0x39
created by github.com/GoogleContainerTools/skaffold/pkg/skaffold/kubernetes.(*PortForwarder).Start.func1
	/go/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/kubernetes/port_forward.go:151 +0x277
```

**Comment by danielllek** [comment]
Hmmm, I can't reproduce it too on 0.18.0.
