### ISSUE TITLE
Experimental GUI is broken on Windows

### ISSUE THREAD

**Issue by WoLfulus** [GoogleContainerTools/skaffold#1658]
### Expected behavior

Show some experimental gui (I'm aware it's experimental) - just reporting

### Actual behavior

```
panic: close of nil channel

goroutine 1 [running]:
github.com/GoogleContainerTools/skaffold/vendor/github.com/gdamore/tcell.(*tScreen).Fini(0xc0424fe000)
        /go/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/gdamore/tcell/tscreen.go:406 +0x224
github.com/GoogleContainerTools/skaffold/vendor/github.com/rivo/tview.(*Application).Stop(0xc0422c4300)
        /go/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/rivo/tview/application.go:273 +0x9c
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.dev(0x1767660, 0xc042004018, 0xc042499c01, 0x1766420, 0xc04258d3c0)
        /go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd/dev.go:110 +0x283
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.NewCmdDev.func1(0xc042284500, 0xc04227e320, 0x0, 0x5, 0x0, 0x0)
        /go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd/dev.go:41 +0x7e
github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra.(*Command).execute(0xc042284500, 0xc04227e2d0, 0x5, 0x5, 0xc042284500, 0xc04227e2d0)
        /go/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra/command.go:762 +0x46f
github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x20f3f60, 0xc042284500, 0xc042284280, 0xc042284000)
        /go/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra/command.go:852 +0x311
github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra.(*Command).Execute(0x20f3f60, 0xc042004018, 0x1767660)
        /go/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra/command.go:800 +0x32
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app.Run(0x0, 0xc042499f78)
        /go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/skaffold.go:32 +0x92
main.main()
        /go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/skaffold.go:29 +0x2d
```

### Information

- Skaffold version: 23
- Operating system: Windows 10 Pro
- Contents of skaffold.yaml: any

**Comment by balopat** [comment]
Thanks for filing this! 
We'll look into this soon. 
cc @dgageot

**Comment by dgageot** [comment]
@balopat I'm going to remove this experimental UI. We'll see if we can do something better in the future
