### ISSUE TITLE
flake: TestDevSync

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#1767]
https://source.cloud.google.com/results/invocations/6a06d995-25be-4c50-8091-c2e0f98ab350/targets/runtimes-common%2Fskaffold%2Fpresubmit/log
````
=== RUN   TestDevSync
Namespace: skaffold7m9xm
Generating tags...
 - gcr.io/k8s-skaffold/test-file-sync -> gcr.io/k8s-skaffold/test-file-sync:c33ece9
Tags generated in 8.393478ms
Starting build...
Building [gcr.io/k8s-skaffold/test-file-sync]...
panic: test timed out after 10m0s
goroutine 362 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1240 +0xfc
created by time.goFunc
	/usr/local/go/src/time/sleep.go:172 +0x44
goroutine 1 [chan receive]:
testing.(*T).Run(0xc420660000, 0x12a9a35, 0xb, 0x1331db0, 0x47f501)
	/usr/local/go/src/testing/testing.go:825 +0x301
testing.runTests.func1(0xc420406000)
	/usr/local/go/src/testing/testing.go:1063 +0x64
testing.tRunner(0xc420406000, 0xc420405df8)
	/usr/local/go/src/testing/testing.go:777 +0xd0
testing.runTests(0xc4200fd9a0, 0x1bacb00, 0xb, 0xb, 0x411eb9)
	/usr/local/go/src/testing/testing.go:1061 +0x2c4
testing.(*M).Run(0xc420302880, 0x0)
	/usr/local/go/src/testing/testing.go:978 +0x171
main.main()
	_testmain.go:62 +0x151
````

**Comment by dgageot** [comment]
I hate this test. I thought I fixed it

**Comment by dgageot** [comment]
It's super strange, it seems to timeout during the build...

When the test is killed, it fails on `/go/src/github.com/GoogleContainerTools/skaffold/integration/sync_test.go:38`. It's stuck on the `select` in `RunSkaffoldNoFail`

**Comment by dgageot** [comment]
This one hasn't failed in a long time
