### ISSUE TITLE
Microservices example: i/o timeout

### ISSUE THREAD

**Issue by andremoeller** [GoogleContainerTools/skaffold#2381]
### Expected behavior

Going through https://github.com/GoogleContainerTools/skaffold/tree/master/examples/microservices,

`curl $(minikube service leeroy-web --url)`

should give

`leeroooooy app!`

### Actual behavior

`curl $(minikube service leeroy-web --url)`

Gives
`curl: (52) Empty reply from server`, and server says:

```
[leeroy-web-7c5796db8d-nqxx4 leeroy-web] 2019/07/01 02:13:33 http: panic serving 172.17.0.1:52820: Get http://leeroy-app:50051: dial tcp: lookup leeroy-app on 10.96.0.10:53: read udp 172.17.0.8:60554->10.96.0.10:53: i/o timeout
[leeroy-web-7c5796db8d-nqxx4 leeroy-web] goroutine 13 [running]:
[leeroy-web-7c5796db8d-nqxx4 leeroy-web] net/http.(*conn).serve.func1(0xc00008caa0)
[leeroy-web-7c5796db8d-nqxx4 leeroy-web] 	/usr/local/go/src/net/http/server.go:1769 +0x139
[leeroy-web-7c5796db8d-nqxx4 leeroy-web] panic(0x6a93a0, 0xc0001ca360)
[leeroy-web-7c5796db8d-nqxx4 leeroy-web] 	/usr/local/go/src/runtime/panic.go:522 +0x1b5
[leeroy-web-7c5796db8d-nqxx4 leeroy-web] main.handler(0x756820, 0xc0001040e0, 0xc000100200)
[leeroy-web-7c5796db8d-nqxx4 leeroy-web] 	/go/web.go:13 +0x190
[leeroy-web-7c5796db8d-nqxx4 leeroy-web] net/http.HandlerFunc.ServeHTTP(0x707f58, 0x756820, 0xc0001040e0, 0xc000100200)
[leeroy-web-7c5796db8d-nqxx4 leeroy-web] 	/usr/local/go/src/net/http/server.go:1995 +0x44
[leeroy-web-7c5796db8d-nqxx4 leeroy-web] net/http.(*ServeMux).ServeHTTP(0x9360c0, 0x756820, 0xc0001040e0, 0xc000100200)
[leeroy-web-7c5796db8d-nqxx4 leeroy-web] 	/usr/local/go/src/net/http/server.go:2375 +0x1d6
[leeroy-web-7c5796db8d-nqxx4 leeroy-web] net/http.serverHandler.ServeHTTP(0xc000096d00, 0x756820, 0xc0001040e0, 0xc000100200)
[leeroy-web-7c5796db8d-nqxx4 leeroy-web] 	/usr/local/go/src/net/http/server.go:2774 +0xa8
[leeroy-web-7c5796db8d-nqxx4 leeroy-web] net/http.(*conn).serve(0xc00008caa0, 0x756da0, 0xc0000208c0)
[leeroy-web-7c5796db8d-nqxx4 leeroy-web] 	/usr/local/go/src/net/http/server.go:1878 +0x851
[leeroy-web-7c5796db8d-nqxx4 leeroy-web] created by net/http.(*Server).Serve
[leeroy-web-7c5796db8d-nqxx4 leeroy-web] 	/usr/local/go/src/net/http/server.go:2884 +0x2f4
```

### Information

- Skaffold version: version: v0.32.0
- Operating system: Ubuntu 18.04
- Contents of skaffold.yaml: https://github.com/GoogleContainerTools/skaffold/blob/master/examples/microservices/skaffold.yaml

### Steps to reproduce the behavior

, then follow the skaffold tutorial

1. `minikube start --vm-driver=none`, with minikube v1.1.1
2. Follow skaffold microservices tutorial

**Comment by andremoeller** [comment]
Closing this: hostnames weren't resolving because coredns pod detected a loop and crashed -- deleted "loop" from coredns config fixed this:

https://stackoverflow.com/questions/52645473/coredns-fails-to-run-in-kubernetes-cluster
