### ISSUE TITLE
TestFlake: TestRun/jib_in_googlecloudbuild

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#2385]
```
=== RUN   TestRun/jib_in_googlecloudbuild
time="2019-07-01T14:19:23Z" level=info msg="Namespace: skaffoldfrfdp"
time="2019-07-01T14:19:23Z" level=info msg="[skaffold run --namespace skaffoldfrfdp -p gcb]"
panic: test timed out after 15m0s
goroutine 191 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1296 +0xfd
created by time.goFunc
	/usr/local/go/src/time/sleep.go:172 +0x44
goroutine 1 [chan receive, 14 minutes]:
testing.(*T).Run(0xc000018d00, 0x1468abd, 0x7, 0x1501438, 0x482401)
	/usr/local/go/src/testing/testing.go:879 +0x383
testing.runTests.func1(0xc000018600)
	/usr/local/go/src/testing/testing.go:1119 +0x78
testing.tRunner(0xc000018600, 0xc00046de08)
	/usr/local/go/src/testing/testing.go:827 +0xbf
testing.runTests(0xc00000dda0, 0x2249600, 0x14, 0x14, 0x40d93f)
	/usr/local/go/src/testing/testing.go:1117 +0x2aa
testing.(*M).Run(0xc000102600, 0x0)
	/usr/local/go/src/testing/testing.go:1034 +0x165
main.main()
	_testmain.go:80 +0x13d
goroutine 5 [chan receive]:
github.com/GoogleContainerTools/skaffold/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x225f560)
	/go/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/golang/glog/glog.go:882 +0x8b
created by github.com/GoogleContainerTools/skaffold/vendor/github.com/golang/glog.init.0
	/go/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/golang/glog/glog.go:410 +0x203
goroutine 52 [syscall, 15 minutes]:
os/signal.signal_recv(0x1503928)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41
goroutine 150 [chan receive]:
testing.(*T).Run(0xc00069c000, 0x147e578, 0x17, 0xc00061a040, 0xc000433701)
	/usr/local/go/src/testing/testing.go:879 +0x383
github.com/GoogleContainerTools/skaffold/integration.TestRun(0xc000018d00)
	/go/src/github.com/GoogleContainerTools/skaffold/integration/run_test.go:113 +0x831
testing.tRunner(0xc000018d00, 0x1501438)
	/usr/local/go/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:878 +0x35c
goroutine 69 [IO wait]:
internal/poll.runtime_pollWait(0x7f641fa5ad60, 0x72, 0xc00006d870)
	/usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc00041b398, 0x72, 0xffffffffffffff00, 0x15fb980, 0x21ed760)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc00041b398, 0xc000273000, 0x1000, 0x1000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc00041b380, 0xc000273000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc00041b380, 0xc000273000, 0x1000, 0x1000, 0x40a82b, 0xc000030000, 0x12ea820)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0000e6008, 0xc000273000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:177 +0x68
crypto/tls.(*block).readFromUntil(0xc000168090, 0x15f9fc0, 0xc0000e6008, 0x5, 0xc0000e6008, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:492 +0x89
crypto/tls.(*Conn).readRecord(0xc000136000, 0x1503b17, 0xc000136120, 0xc00049a380)
	/usr/local/go/src/crypto/tls/conn.go:593 +0xdd
crypto/tls.(*Conn).Read(0xc000136000, 0xc000312000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1145 +0xf1
bufio.(*Reader).Read(0xc000010300, 0xc00034e038, 0x9, 0x9, 0xc00049a380, 0xc00006dc58, 0xc00006dc70)
	/usr/local/go/src/bufio/bufio.go:216 +0x22f
io.ReadAtLeast(0x15f7ea0, 0xc000010300, 0xc00034e038, 0x9, 0x9, 0x9, 0xc00006dcf8, 0x8149fb, 0xc00048f9e0)
	/usr/local/go/src/io/io.go:310 +0x88
io.ReadFull(0x15f7ea0, 0xc000010300, 0xc00034e038, 0x9, 0x9, 0xc00006dd28, 0x81490d, 0xc00006dfb8)
	/usr/local/go/src/io/io.go:329 +0x58
github.com/GoogleContainerTools/skaffold/vendor/golang.org/x/net/http2.readFrameHeader(0xc00034e038, 0x9, 0x9, 0x15f7ea0, 0xc000010300, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/GoogleContainerTools/skaffold/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/GoogleContainerTools/skaffold/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc00034e000, 0xc0005967e0, 0x0, 0x0, 0x0)
	/go/src/github.com/GoogleContainerTools/skaffold/vendor/golang.org/x/net/http2/frame.go:492 +0xa3
github.com/GoogleContainerTools/skaffold/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc00006dfb8, 0x1502978, 0xc0004adfb8)
	/go/src/github.com/GoogleContainerTools/skaffold/vendor/golang.org/x/net/http2/transport.go:1658 +0x9e
github.com/GoogleContainerTools/skaffold/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc00010a8c0)
	/go/src/github.com/GoogleContainerTools/skaffold/vendor/golang.org/x/net/http2/transport.go:1586 +0x76
created by github.com/GoogleContainerTools/skaffold/vendor/golang.org/x/net/http2.(*Transport).newClientConn
	/go/src/github.com/GoogleContainerTools/skaffold/vendor/golang.org/x/net/http2/transport.go:660 +0x636
goroutine 103 [select, 14 minutes]:
net/http.(*persistConn).writeLoop(0xc000210900)
	/usr/local/go/src/net/http/transport.go:1885 +0x113
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1339 +0x966
goroutine 207 [syscall]:
syscall.Syscall6(0xf7, 0x1, 0x2925, 0xc000441ae0, 0x1000004, 0x0, 0x0, 0x60, 0xc0006aa240, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
os.(*Process).blockUntilWaitable(0xc0003328a0, 0x6, 0xc000441c48, 0xc0003328a0)
	/usr/local/go/src/os/wait_waitid.go:31 +0x98
os.(*Process).wait(0xc0003328a0, 0x50, 0x48, 0xc0002745f0)
	/usr/local/go/src/os/exec_unix.go:22 +0x39
os.(*Process).Wait(0xc0003328a0, 0x15036b8, 0x15036c0, 0x15036b0)
	/usr/local/go/src/os/exec.go:125 +0x2b
os/exec.(*Cmd).Wait(0xc0005a2580, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:465 +0x5b
os/exec.(*Cmd).Run(0xc0005a2580, 0xc0006745a0, 0x344571300000001)
	/usr/local/go/src/os/exec/exec.go:309 +0x5c
os/exec.(*Cmd).Output(0xc0005a2580, 0xc8b6e9ed9a, 0x225f020, 0xc000546ac0, 0x20, 0x13404c0)
	/usr/local/go/src/os/exec/exec.go:504 +0xf1
github.com/GoogleContainerTools/skaffold/integration/skaffold.(*RunBuilder).RunOrFailOutput(0xc000441f10, 0xc00069c000, 0xc0005968d0, 0xc000546a60, 0x21ea048)
	/go/src/github.com/GoogleContainerTools/skaffold/integration/skaffold/helper.go:186 +0x137
github.com/GoogleContainerTools/skaffold/integration.TestRun.func1(0xc00069c000)
	/go/src/github.com/GoogleContainerTools/skaffold/integration/run_test.go:124 +0x1c1
testing.tRunner(0xc00069c000, 0xc00061a040)
	/usr/local/go/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:878 +0x35c
goroutine 102 [select, 14 minutes]:
net/http.(*persistConn).readLoop(0xc000210900)
	/usr/local/go/src/net/http/transport.go:1761 +0x6b9
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1338 +0x941
goroutine 259 [select]:
os/exec.(*Cmd).Start.func2(0xc0005a2580)
	/usr/local/go/src/os/exec/exec.go:407 +0xc4
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:406 +0x64d
goroutine 209 [IO wait]:
internal/poll.runtime_pollWait(0x7f641fa5ae30, 0x72, 0xc0004ab4e8)
	/usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc00048fbd8, 0x72, 0xffffffffffffff01, 0x15fb980, 0x21ed760)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc00048fbd8, 0xc000590701, 0x634, 0x634)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc00048fbc0, 0xc0005907cc, 0x634, 0x634, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x179
os.(*File).read(0xc0000e6630, 0xc0005907cc, 0x634, 0x634, 0x41, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:249 +0x4e
os.(*File).Read(0xc0000e6630, 0xc0005907cc, 0x634, 0x634, 0x41, 0x0, 0x0)
	/usr/local/go/src/os/file.go:108 +0x69
bytes.(*Buffer).ReadFrom(0xc0004818f0, 0x15fa2a0, 0xc0000e6630, 0x7f641f9b6020, 0xc0004818f0, 0x1)
	/usr/local/go/src/bytes/buffer.go:206 +0xbd
io.copyBuffer(0x15f7f00, 0xc0004818f0, 0x15fa2a0, 0xc0000e6630, 0x0, 0x0, 0x0, 0x0, 0xc00069c600, 0xc0006b8000)
	/usr/local/go/src/io/io.go:388 +0x303
io.Copy(0x15f7f00, 0xc0004818f0, 0x15fa2a0, 0xc0000e6630, 0x8185b2, 0xc00017f540, 0x7f641fa0fea8)
	/usr/local/go/src/io/io.go:364 +0x5a
os/exec.(*Cmd).writerDescriptor.func1(0x7f641fa0fea8, 0xc00048fa40)
	/usr/local/go/src/os/exec/exec.go:279 +0x4d
os/exec.(*Cmd).Start.func1(0xc0005a2580, 0xc000546b80)
	/usr/local/go/src/os/exec/exec.go:400 +0x27
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:399 +0x5af
goroutine 258 [IO wait]:
internal/poll.runtime_pollWait(0x7f641fa5af00, 0x72, 0xc000433558)
	/usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc00048fc98, 0x72, 0xffffffffffffff01, 0x15fb980, 0x21ed760)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc00048fc98, 0xc00060e001, 0x8000, 0x8000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc00048fc80, 0xc00060e000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x179
os.(*File).read(0xc0000e6658, 0xc00060e000, 0x8000, 0x8000, 0xc000433658, 0x48b8ec, 0xc000433660)
	/usr/local/go/src/os/file_unix.go:249 +0x4e
os.(*File).Read(0xc0000e6658, 0xc00060e000, 0x8000, 0x8000, 0x8000, 0x8000, 0x4)
	/usr/local/go/src/os/file.go:108 +0x69
io.copyBuffer(0x15fa3a0, 0xc0006745a0, 0x15fa2a0, 0xc0000e6658, 0xc00060e000, 0x8000, 0x8000, 0xc0000e03c0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:402 +0x125
io.Copy(0x15fa3a0, 0xc0006745a0, 0x15fa2a0, 0xc0000e6658, 0x406a35, 0xc0000e0540, 0xc0004337b0)
	/usr/local/go/src/io/io.go:364 +0x5a
os/exec.(*Cmd).writerDescriptor.func1(0xc0000e0540, 0xc0004337b0)
	/usr/local/go/src/os/exec/exec.go:279 +0x4d
os/exec.(*Cmd).Start.func1(0xc0005a2580, 0xc000546be0)
	/usr/local/go/src/os/exec/exec.go:400 +0x27
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:399 +0x5af
FAIL	github.com/GoogleContainerTools/skaffold/integration	900.030s
make: *** [integration] Error 1
Makefile:107: recipe for target 'integration' failed
make: *** [integration-in-docker] Error 2

```

**Comment by dgageot** [comment]
Let's close this one
