### ISSUE TITLE
skaffold init can't be interrupted with ctrl-c

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#2512]

**Comment by dgageot** [comment]
When I run `skaffold init` and press ctrl-c when a question is asked to me, I expect the whole process to be interrupted. It's not

**Comment by nkubala** [comment]
yeah I actually get something even worse when I run this on the `microservices` example:

```
➜  microservices git:(master) ✗ skaffold init
? Choose the builder to build image gcr.io/k8s-skaffold/leeroy-app  [Use arrows to move, space to select, type to filter]
> Docker (leeroy-app/Dockerfile)
  Docker (leeroy-web/Dockerfile)
  None (image not built from these sources)
? Choose the builder to build image gcr.io/k8s-skaffold/leeroy-web  [Use arrows to move, space to select, type to filter]
> Docker (leeroy-app/Dockerfile)
  Docker (leeroy-web/Dockerfile)
  None (image not built from these sources)
WARN[0002] unused builder configs found in repository: [{leeroy-app/Dockerfile} {leeroy-web/Dockerfile}]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x51f7cfd]

goroutine 1 [running]:
github.com/GoogleContainerTools/skaffold/pkg/skaffold/initializer.processBuildArtifacts(0xc000824100, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	pkg/skaffold/initializer/init.go:383 +0xfd
github.com/GoogleContainerTools/skaffold/pkg/skaffold/initializer.generateSkaffoldConfig(0x5897e60, 0xc0002041e0, 0xc000824100, 0x2, 0x2, 0x2, 0x2, 0x2, 0x2, 0xc0002d2940)
	pkg/skaffold/initializer/init.go:402 +0x137
github.com/GoogleContainerTools/skaffold/pkg/skaffold/initializer.DoInit(0x58c33e0, 0xc000343940, 0x588c800, 0xc0000e8000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	pkg/skaffold/initializer/init.go:167 +0x3da
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.doInit(0x58c33e0, 0xc000343940, 0x588c800, 0xc0000e8000, 0xc0003023e0, 0xc000030f00)
	cmd/skaffold/app/cmd/init.go:55 +0x151
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.cancelWithCtrlC.func1(0x588c800, 0xc0000e8000, 0x0, 0x0)
	cmd/skaffold/app/cmd/signals.go:33 +0xba
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.(*builder).NoArgs.func1(0xc0002f8280, 0x68560a8, 0x0, 0x0, 0x0, 0x0)
	cmd/skaffold/app/cmd/commands.go:96 +0x6b
github.com/spf13/cobra.(*Command).execute(0xc0002f8280, 0x68560a8, 0x0, 0x0, 0xc0002f8280, 0x68560a8)
	vendor/github.com/spf13/cobra/command.go:826 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc000030f00, 0xc0000e8000, 0x588c800, 0xc0000e8008)
	vendor/github.com/spf13/cobra/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	vendor/github.com/spf13/cobra/command.go:864
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app.Run(0x588c800, 0xc0000e8000, 0x588c800, 0xc0000e8008, 0xc0004b3f88, 0x400781f)
	cmd/skaffold/app/skaffold.go:27 +0x58
main.main()
	cmd/skaffold/skaffold.go:30 +0x4e
```

**Comment by tejal29** [comment]
Bumping down the priority since, we are not actively working on this at the moment.
