### ISSUE TITLE
Panic during skaffold diagnose with custom builder

### ISSUE THREAD

**Issue by tbarrella** [GoogleContainerTools/skaffold#2683]
(doesn't seem high pri, but tracking this)

### Actual behavior
```
Skaffold version: a1efe8cc46e7584ad71c2f140cbfb94c1b4d82ff
Configuration version: skaffold/v1beta13
Number of artifacts: 1

Unknown artifact: <repo>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x129a01e]

goroutine 1 [running]:
github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/custom.GetDependencies(0x1995e20, 0xc0000be010, 0x171dd45, 0x1, 0xc0000b5280, 0xc00022d6e0, 0x0, 0x1f3, 0x1e, 0xc000553900, ...)
	/go/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/custom/dependencies.go:35 +0x3e
github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/local.(*Builder).DependenciesForArtifact(0xc00038acd0, 0x1995e20, 0xc0000be010, 0xc00029f380, 0xc0005538e8, 0x4b22c6, 0x5d5af3f5, 0x3530a9f, 0x2213de73b5a330)
	/go/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/local/local.go:117 +0xbe
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.timeToListDependencies(0x1995e20, 0xc0000be010, 0x7f0dc2ccc378, 0xc0002213c0, 0xc00029f380, 0xc000553a70, 0x2, 0x2, 0x5d, 0x0, ...)
	/go/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner/diagnose.go:109 +0x95
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.(*SkaffoldRunner).DiagnoseArtifacts(0xc000240b40, 0x195cf00, 0xc0000ca008, 0x2, 0x2)
	/go/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner/diagnose.go:50 +0x2f3
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.doDiagnose.func1(0x19b17c0, 0xc000240b40, 0xc000025d00, 0xc000025d00, 0x0)
	/go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd/diagnose.go:52 +0x334
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.withRunner(0x1995de0, 0xc000087a00, 0xc000553c70, 0x1937a08, 0x19779e0)
	/go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd/runner.go:47 +0x72
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.doDiagnose(0x1995de0, 0xc000087a00, 0x195cf00, 0xc0000ca008, 0xc0000133b0, 0xc000347b80)
	/go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd/diagnose.go:47 +0x70
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.cancelWithCtrlC.func1(0x195cf00, 0xc0000ca008, 0x0, 0x0)
	/go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd/signals.go:33 +0xba
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.(*builder).NoArgs.func1(0xc000373400, 0x27fd8a8, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd/commands.go:96 +0x6b
github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra.(*Command).execute(0xc000373400, 0x27fd8a8, 0x0, 0x0, 0xc000373400, 0x27fd8a8)
	/go/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra/command.go:762 +0x465
github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000347b80, 0xc0000ca008, 0x195cf00, 0xc0000ca010)
	/go/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra/command.go:800
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app.Run(0x195cf00, 0xc0000ca008, 0x195cf00, 0xc0000ca010, 0xc0004d9f88, 0x40584f)
	/go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/skaffold.go:27 +0x58
main.main()
	/go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/skaffold.go:30 +0x4e
```
### Information

- Skaffold version: v0.36.0
- Operating system: Ubuntu 16.04
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: <repo>
      custom:
        buildCommand: ./build.sh
```

### Steps to reproduce the behavior

1. Use any `build.sh`
2. `skaffold diagnose`

**Comment by balopat** [comment]
Thank you @tbarrella, yupp it looks like we missed something here. 
I think we should add `skaffold diagnose` on all our examples. 
That should cover most of our builders, deployers. Good first issue for someone interested in contributing to Skaffold!
