### ISSUE TITLE
panic: interface conversion: interface {} is int, not string

### ISSUE THREAD

**Issue by hugoduncan** [GoogleContainerTools/skaffold#2918]
When running `skaffold run` with a helm release, skaffold panics.

The panic seems to be caused by a `ConfigMap` in the chart, that uses port numbers for keys (for nginx-ingress configuration).

```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: myapp
    chart: myapp-0.1.0
    release: myapp
  name: rel-nginx-ingress-tcp
data:
  1973: "test/myservice:1973"
```

### Expected behavior

`skaffold run` runs without error

### Actual behavior
```
[storage] 2019/09/20 07:52:48 getting last revision of "myrelease"
[storage] 2019/09/20 07:52:48 getting release history for "myrelease"
panic: interface conversion: interface {} is int, not string

goroutine 1 [running]:
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy/kubectl.recursiveVisit(0x53411a0, 0xc000799710, 0x5848040, 0xc0005d61a0)
	pkg/skaffold/deploy/kubectl/visitor.go:73 +0x51f
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy/kubectl.recursiveVisit(0x53411a0, 0xc0007995f0, 0x5848040, 0xc0005d61a0)
	pkg/skaffold/deploy/kubectl/visitor.go:89 +0x33b
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy/kubectl.(*ManifestList).Visit(0xc000838998, 0x5848040, 0xc0005d61a0, 0x3, 0xc000838908, 0x400e526, 0xc0005d6180, 0x20)
	pkg/skaffold/deploy/kubectl/visitor.go:47 +0x1df
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy/kubectl.(*ManifestList).CollectNamespaces(0xc000838998, 0xc0005d6180, 0x136, 0xc00083898e, 0xa, 0xa)
	pkg/skaffold/deploy/kubectl/namespaces.go:30 +0x8a
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy.getObjectNamespaceIfDefined(0xc000a44780, 0x117, 0x136, 0xc0002ac4d8, 0x4, 0x0, 0x2, 0x4, 0x0)
	pkg/skaffold/deploy/util.go:75 +0x11e
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy.parseReleaseInfo(0xc0002ac4d8, 0x4, 0xc0002bb020, 0xc0004d0750, 0x8, 0xc0002bb020)
	pkg/skaffold/deploy/util.go:57 +0x1d4
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy.(*HelmDeployer).getDeployResults(0xc00003c1c0, 0x585d9c0, 0xc0000e3c80, 0xc0002ac4d8, 0x4, 0xc0004d0750, 0x8, 0xe, 0x10, 0x0)
	pkg/skaffold/deploy/helm.go:426 +0xf3
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy.(*HelmDeployer).deployRelease(0xc00003c1c0, 0x585d9c0, 0xc0000e3c80, 0x581d7e0, 0xc0000ce000, 0xc0002ac4b8, 0x8, 0xc000664e00, 0x11, 0xc00066ac20, ...)
	pkg/skaffold/deploy/helm.go:353 +0x1954
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy.(*HelmDeployer).Deploy(0xc00003c1c0, 0x585d9c0, 0xc0000e3c80, 0x581d7e0, 0xc0000ce000, 0xc0003f8140, 0x2, 0x2, 0xc000580280, 0x5, ...)
	pkg/skaffold/deploy/helm.go:82 +0x65e
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.withTimings.Deploy(0x5866bc0, 0xc000580140, 0x5831640, 0xc00003c140, 0x585dc40, 0xc00003c1c0, 0x1, 0x585d9c0, 0xc0000e3c80, 0x581d7e0, ...)
	pkg/skaffold/runner/timings.go:89 +0x15f
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.(*SkaffoldRunner).Deploy(0xc00056a480, 0x585d9c0, 0xc0000e3c80, 0x581d7e0, 0xc0000ce000, 0xc0003f8140, 0x2, 0x2, 0x2, 0x0)
	pkg/skaffold/runner/deploy.go:39 +0xfe
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.(*SkaffoldRunner).DeployAndLog(0xc00056a480, 0x585d9c0, 0xc0000e3c80, 0x581d7e0, 0xc0000ce000, 0xc0003f8140, 0x2, 0x2, 0x0, 0x0)
	pkg/skaffold/runner/build_deploy.go:89 +0x434
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.doRun.func1(0x587f940, 0xc00056a480, 0xc0003b2400, 0x0, 0x10001000001)
	cmd/skaffold/app/cmd/run.go:52 +0x126
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.withRunner(0x585d9c0, 0xc0000e3c80, 0xc0005dfbf8, 0xc0000b3bc0, 0x58322c0)
	cmd/skaffold/app/cmd/runner.go:48 +0xa7
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.doRun(0x585d9c0, 0xc0000e3c80, 0x581d7e0, 0xc0000ce000, 0xc0002f7bf0, 0x1a)
	cmd/skaffold/app/cmd/run.go:46 +0x83
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.cancelWithCtrlC.func1(0x581d7e0, 0xc0000ce000, 0x0, 0x0)
	cmd/skaffold/app/cmd/signals.go:33 +0xe1
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.(*builder).NoArgs.func1(0xc00057ac80, 0xc00000f6c0, 0x0, 0x2, 0x0, 0x0)
	cmd/skaffold/app/cmd/commands.go:96 +0x6a
github.com/spf13/cobra.(*Command).execute(0xc00057ac80, 0xc00000f680, 0x2, 0x2, 0xc00057ac80, 0xc00000f680)
	vendor/github.com/spf13/cobra/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc00057aa00, 0xc0000ce000, 0x581d7e0, 0xc0000d0000)
	vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	vendor/github.com/spf13/cobra/command.go:864
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app.Run(0x581d7e0, 0xc0000ce000, 0x581d7e0, 0xc0000d0000, 0xc00049df50, 0x4007d8f)
	cmd/skaffold/app/skaffold.go:27 +0x57
main.main()
	cmd/skaffold/skaffold.go:30 +0x4e
```
### Information

- Skaffold version: v0.38.0
- Operating system: Mac OS X
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta14
kind: Config
metadata:
  name: myproj
build:
  local:
    push: false
  artifacts:
  - image: image
    context: .
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: myrel
        namespace: default
        chartPath: mychart
        values:
          image.repository: image
```

### Steps to reproduce the behavior

1. git clone git@github.com:hugoduncan/skaffold-issue.git
2. `skaffold run`

**Comment by balopat** [comment]
Thank you for filing! This seems to be a bug due to a falsy assumption on the type of the keys here:

https://github.com/GoogleContainerTools/skaffold/blob/43e326aaebc48a1d2c17b374ac77a84ac8a45b9e/pkg/skaffold/deploy/kubectl/visitor.go#L73-L74

It should be relatively easy to fix this, here's a rough outline if somebody wants to raise a PR: 
- [ ] write a unit test to cover the case in visitor_test.go, something like 
```
{
			description: "single manifest in the list with matched key and string value",
			manifests: ManifestList{[]byte(`
123: match-value
1234: not-replaced`)},
			matchValues: []string{"match-value"},
			expected: ManifestList{[]byte(`
123: match-value
1234: replaced`)},
		},
```
- [ ] fix the issue by changing the key type to `interface{}`
