### ISSUE TITLE
skaffold init --skip-build nil pointer dereference

### ISSUE THREAD

**Issue by saphoooo** [GoogleContainerTools/skaffold#3692]
Because I use to use buildpack, I don't have Dockerfile in the folder during the `init`

### Expected behavior

A skaffold.yaml file with initial content.

### Actual behavior

```
skaffold init --skip-build
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x513b3a5]

goroutine 1 [running]:
github.com/GoogleContainerTools/skaffold/pkg/skaffold/initializer.(*builderAnalyzer).enterDir(0x0, 0x5584c75, 0x1)
	<autogenerated>:1 +0x5
github.com/GoogleContainerTools/skaffold/pkg/skaffold/initializer.(*analysis).analyze(0xc0005b3730, 0x5584c75, 0x1, 0x80, 0xc0002d2540)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/initializer/analyze.go:63 +0xfb
github.com/GoogleContainerTools/skaffold/pkg/skaffold/initializer.DoInit(0x589dc40, 0xc000098e80, 0x5857de0, 0xc0000c0008, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/initializer/init.go:86 +0x14e
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.doInit(0x589dc40, 0xc000098e80, 0x5857de0, 0xc0000c0008, 0xc000334680, 0xf)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd/init.go:70 +0x1db
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.cancelWithCtrlC.func1(0x5857de0, 0xc0000c0008, 0x0, 0x0)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd/signals.go:33 +0xe1
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.(*builder).NoArgs.func1(0xc00040a780, 0xc0003345e0, 0x0, 0x1, 0x0, 0x0)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd/commands.go:96 +0x6a
github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra.(*Command).execute(0xc00040a780, 0xc0003345c0, 0x1, 0x1, 0xc00040a780, 0xc0003345c0)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra/command.go:826 +0x460
github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000132c80, 0xc0000c0008, 0x5857de0, 0xc0000c0010)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra/command.go:864
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app.Run(0x5857de0, 0xc0000c0008, 0x5857de0, 0xc0000c0010, 0xc0005b3f50, 0x400759f)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/skaffold.go:27 +0x57
main.main()
	/ext-go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/skaffold.go:30 +0x4e
```

### Information

- Skaffold version: v1.3.1
- Operating system: MacOS 10.15.3 and Unbuntu 18.04

### Steps to reproduce the behavior

1.  Create an empty dir with a deployment.yaml file
2. `skaffold init --skip-build`

**Comment by dgageot** [comment]
Hi @saphoooo! This should be fixed with https://github.com/GoogleContainerTools/skaffold/pull/3657. Can you confirm?

**Comment by saphoooo** [comment]
Looks fine:

```
$ skaffold init --skip-buildapiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: loto
deploy:
  kubectl:
    manifests:
    - deploy.yaml

Do you want to write this configuration to skaffold.yaml? [y/n]: y
Configuration skaffold.yaml was written
```

Thank you
