### ISSUE TITLE
SIGILL: illegal instruction on macOS on versions >= 1.6.0

### ISSUE THREAD

**Issue by jordanworner** [GoogleContainerTools/skaffold#4008]
### Expected behavior

Skaffold commands to execute successfully without a SIGILL error on macOS

### Actual behavior

All commands in skaffold versions >= 1.6.0 are throwing SIGILL errors

SIGILL: illegal instruction
PC=0x4067380 m=0 sigcode=1
goroutine 1 [running, locked to thread]:
runtime.asyncPreempt()
        /usr/local/go/src/runtime/preempt_amd64.s:8 fp=0xc00009ddb8 sp=0xc00009ddb0 pc=0x4067380
net.ParseCIDR(0x567b788, 0x7, 0xc00009de01, 0xc0000c6390, 0xc00009de00, 0x400fddd, 0x55bc120, 0xc0000c6390)
        /usr/local/go/src/net/ip.go:712 fp=0xc00009ddc0 sp=0xc00009ddb8 pc=0x416e500
net.mustCIDR(0x567b788, 0x7, 0x597b3e0)
        /usr/local/go/src/net/addrselect.go:295 +0x39 fp=0xc00009de10 sp=0xc00009ddc0 pc=0x4157909
net.init()
        /usr/local/go/src/net/addrselect.go:227 +0x4d4 fp=0xc00009de68 sp=0xc00009de10 pc=0x418cf84
runtime.doInit(0x66e20e0)
        /usr/local/go/src/runtime/proc.go:5414 +0x8a fp=0xc00009de98 sp=0xc00009de68 pc=0x404462a
runtime.doInit(0x66e1320)
        /usr/local/go/src/runtime/proc.go:5409 +0x57 fp=0xc00009dec8 sp=0xc00009de98 pc=0x40445f7
runtime.doInit(0x66e1e60)
        /usr/local/go/src/runtime/proc.go:5409 +0x57 fp=0xc00009def8 sp=0xc00009dec8 pc=0x40445f7
runtime.doInit(0x66e9c80)
        /usr/local/go/src/runtime/proc.go:5409 +0x57 fp=0xc00009df28 sp=0xc00009def8 pc=0x40445f7
runtime.doInit(0x66d4a40)
        /usr/local/go/src/runtime/proc.go:5409 +0x57 fp=0xc00009df58 sp=0xc00009df28 pc=0x40445f7
runtime.doInit(0x66d5d00)
        /usr/local/go/src/runtime/proc.go:5409 +0x57 fp=0xc00009df88 sp=0xc00009df58 pc=0x40445f7
runtime.main()
        /usr/local/go/src/runtime/proc.go:190 +0x1ce fp=0xc00009dfe0 sp=0xc00009df88 pc=0x4037b3e
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00009dfe8 sp=0xc00009dfe0 pc=0x4065b11

### Information

- Skaffold version: >= 1.6.0
- Operating system: Catalina 10.15.4

Model Name:	Mac Pro
Model Identifier:	MacPro5,1
Processor Name:	6-Core Intel Xeon
Processor Speed:	3.33 GHz
Number of Processors:	2
Total Number of Cores:	12
L2 Cache (per Core):	256 KB
L3 Cache (per Processor):	12 MB
Hyper-Threading Technology:	Enabled
Memory:	32 GB
Boot ROM Version:	144.0.0.0.0

The issue is probably linked to https://github.com/golang/go/issues/37478 because the cross compiling Dockerfile was changed between versions 1.5.0 and 1.6.0. There is a fix for this issue in go1.14.1, the cross compiling Dockerfile looks to be using the previous version.

### Steps to reproduce the behavior

- Install skaffold on a pre AVX mac
- Run a skaffold command

**Comment by jordanworner** [comment]
Thanks @dgageot, just downloaded the latest build and it's working on my Mac.
