### ISSUE TITLE
crash in docker.readCopyCommand when new file appears

### ISSUE THREAD

**Issue by drewpca** [GoogleContainerTools/skaffold#4577]
skaffold dev (1.12.1) was running and refreshing on changes, and suddenly it crashed as follows. I think it was right when `ssh-keygen` had just created a new file, perhaps using an unconventional write pattern or making a file without 'read' perms.

Repro is awkward since I don't know a workaround for https://github.com/GoogleContainerTools/skaffold/issues/4576

```
panic: runtime error: slice bounds out of range [:-1]

goroutine 1 [running]:
github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker.readCopyCommand(0xc000526620, 0xc000b9ecf8, 0x0, 0x0, 0xc000a13d74, 0x4, 0x2, 0x4, 0x0)
        /skaffold/pkg/skaffold/docker/parse.go:258 +0x89c
github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker.extractCopyCommands(0xc0005550e0, 0x12, 0x12, 0xc00053a400, 0xc00053a450, 0x12, 0x12, 0x0, 0x0, 0xc0003f86b8)
        /skaffold/pkg/skaffold/docker/parse.go:219 +0x3e6
github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker.readCopyCmdsFromDockerfile(0x0, 0xc0009d3320, 0x1c, 0x1d75b95, 0x1, 0x0, 0xc00053a450, 0x0, 0x0, 0x0, ...)
        /skaffold/pkg/skaffold/docker/parse.go:89 +0x376
github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker.GetDependencies(0x2131ee0, 0xc000130ec0, 0x1d75b95, 0x1, 0x1d7eb3c, 0xa, 0x0, 0xc00053a450, 0x8, 0x30, ...)
        /skaffold/pkg/skaffold/docker/dependencies.go:61 +0x24c
github.com/GoogleContainerTools/skaffold/pkg/skaffold/build.DependenciesForArtifact(0x2131ee0, 0xc000130ec0, 0xc000598c60, 0xc00053a450, 0xc000c85c50, 0xc000b9f230, 0x40d77d, 0x1caa300, 0xc000c85c50)
        /skaffold/pkg/skaffold/build/dependencies.go:42 +0x473
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.(*SkaffoldRunner).Dev.func2(0xc000c85c50, 0x1871c76, 0x196ec40, 0x0, 0x0)
        /skaffold/pkg/skaffold/runner/dev.go:151 +0x57
github.com/GoogleContainerTools/skaffold/pkg/skaffold/filemon.Stat(0xc0005ca510, 0x0, 0xc000b9f2b8, 0x0)
        /skaffold/pkg/skaffold/filemon/changes.go:35 +0x4a
github.com/GoogleContainerTools/skaffold/pkg/skaffold/filemon.(*watchList).Run(0xc00094f3c0, 0x0, 0x0, 0x0)
        /skaffold/pkg/skaffold/filemon/monitor.go:68 +0xa1
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.(*SkaffoldListener).do(0xc0005ca480, 0xc0008d1780, 0x3, 0x2)
        /skaffold/pkg/skaffold/runner/listen.go:80 +0x4e
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.(*SkaffoldListener).WatchForChanges(0xc0005ca480, 0x2131ee0, 0xc000130ec0, 0x20ea760, 0xc00012c008, 0xc0008d1780, 0x0, 0x0)
        /skaffold/pkg/skaffold/runner/listen.go:72 +0x35d
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.(*SkaffoldRunner).Dev(0xc000434780, 0x2131ee0, 0xc000130ec0, 0x20ea760, 0xc00012c008, 0xc00051ea68, 0x1, 0x1, 0x0, 0x0)
        /skaffold/pkg/skaffold/runner/dev.go:245 +0x14af
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.runDev.func5(0x2153960, 0xc000434780, 0xc0000f7200, 0x0, 0x1010100010001)
        /skaffold/cmd/skaffold/app/cmd/dev.go:63 +0xad
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.withRunner(0x2131ee0, 0xc000130ec0, 0xc00093fc10, 0x1dd0cd6, 0x32)
        /skaffold/cmd/skaffold/app/cmd/runner.go:49 +0x12b
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.runDev(0x2131ee0, 0xc000130ec0, 0x20ea760, 0xc00012c008, 0x0, 0x0)
        /skaffold/cmd/skaffold/app/cmd/dev.go:62 +0x165
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.(*builder).NoArgs.func1(0xc000156b00, 0xc000658c50, 0x0, 0x1, 0x0, 0x0)
        /skaffold/cmd/skaffold/app/cmd/commands.go:105 +0x98
github.com/spf13/cobra.(*Command).execute(0xc000156b00, 0xc000658c40, 0x1, 0x1, 0xc000156b00, 0xc000658c40)
        /skaffold/vendor/github.com/spf13/cobra/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc000156000, 0xc00012c008, 0x20ea760, 0xc00012c010)
        /skaffold/vendor/github.com/spf13/cobra/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /skaffold/vendor/github.com/spf13/cobra/command.go:887
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /skaffold/vendor/github.com/spf13/cobra/command.go:880
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app.Run(0x20ea760, 0xc00012c008, 0x20ea760, 0xc00012c010, 0x0, 0x0)
        /skaffold/cmd/skaffold/app/skaffold.go:33 +0xde
main.main()
        /skaffold/cmd/skaffold/skaffold.go:31 +0x4e
```

**Comment by briandealwis** [comment]
Would you be able to share your Dockerfile?  This code is trying to parse `COPY` and `ADD` commands within the Dockefile to determine the source files/directories.  Something is confusing it.

**Comment by briandealwis** [comment]
@drewpca would you be able to include your Dockerfile?

**Comment by drewpca** [comment]
Came across an easier repro of the same panic. Just take a working setup such as examples/getting-started and append to Dockerfile a line that just says "COPY" (no args). This could happen e.g. if your editor autosaves while you're looking up the filename to copy. Here it is in skaffold v1.14.0:

```
drewpca-laptop(pts/1):~/Downloads/skaffold/examples/getting-started% echo "COPY" >> Dockerfile 
drewpca-laptop(pts/1):~/Downloads/skaffold/examples/getting-started% skaffold dev             
Listing files to watch...
 - skaffold-example
panic: runtime error: slice bounds out of range [:-1]

goroutine 1 [running]:
github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker.readCopyCommand(0xc00032f500, 0xc00086e6a0, 0x1, 0x1, 0x1dab196, 0x1, 0x0, 0x0, 0x0)
	/skaffold/pkg/skaffold/docker/parse.go:278 +0x89c
github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker.extractCopyCommands(0xc0002e50c0, 0x8, 0x8, 0xc00058bd00, 0xc00058bda0, 0x8, 0x8, 0x0, 0x0, 0xc000c24928)
	/skaffold/pkg/skaffold/docker/parse.go:239 +0x3e6
github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker.readCopyCmdsFromDockerfile(0x0, 0xc000990910, 0x44, 0x1dab195, 0x1, 0x0, 0xc00058bda0, 0x0, 0x0, 0x0, ...)
	/skaffold/pkg/skaffold/docker/parse.go:90 +0x376
github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker.GetDependencies(0x21737e0, 0xc000490080, 0x1dab195, 0x1, 0x1db41fa, 0xa, 0x0, 0xc00058bda0, 0x498202, 0x30, ...)
	/skaffold/pkg/skaffold/docker/dependencies.go:61 +0x24c
github.com/GoogleContainerTools/skaffold/pkg/skaffold/build.DependenciesForArtifact(0x21737e0, 0xc000490080, 0xc000184600, 0xc00058bda0, 0xc000c212c0, 0xc0005d7408, 0x40da0d, 0x1cdd7a0, 0xc000c212c0)
	/skaffold/pkg/skaffold/build/dependencies.go:42 +0x473
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.(*SkaffoldRunner).Dev.func2(0xc000c212c0, 0x203000, 0x47072c, 0x30d8080, 0x203000)
	/skaffold/pkg/skaffold/runner/dev.go:151 +0x57
github.com/GoogleContainerTools/skaffold/pkg/skaffold/filemon.Stat(0xc000c21260, 0x1, 0x1, 0x1d)
	/skaffold/pkg/skaffold/filemon/changes.go:35 +0x4a
github.com/GoogleContainerTools/skaffold/pkg/skaffold/filemon.(*watchList).Register(0xc000888040, 0xc000c21260, 0xc000c21290, 0x1dada2f, 0x6)
	/skaffold/pkg/skaffold/filemon/monitor.go:47 +0x2f
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.(*SkaffoldRunner).Dev(0xc000446fc0, 0x21737e0, 0xc000490080, 0x212b9e0, 0xc00012c000, 0xc00012c6f0, 0x1, 0x1, 0x0, 0x0)
	/skaffold/pkg/skaffold/runner/dev.go:149 +0x415
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.runDev.func5(0x2192420, 0xc000446fc0, 0xc0003f3900, 0x0, 0x10100010001)
	/skaffold/cmd/skaffold/app/cmd/dev.go:64 +0xad
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.withRunner(0x21737e0, 0xc000490080, 0xc0005d7bc0, 0x1e06f69, 0x32)
	/skaffold/cmd/skaffold/app/cmd/runner.go:49 +0x12b
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.runDev(0x21737e0, 0xc000490080, 0x212b9e0, 0xc00012c000, 0x0, 0x0)
	/skaffold/cmd/skaffold/app/cmd/dev.go:63 +0x165
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.(*builder).NoArgs.func1(0xc0001542c0, 0x3132a30, 0x0, 0x0, 0x0, 0x0)
	/skaffold/cmd/skaffold/app/cmd/commands.go:111 +0x98
github.com/spf13/cobra.(*Command).execute(0xc0001542c0, 0x3132a30, 0x0, 0x0, 0xc0001542c0, 0x3132a30)
	/skaffold/vendor/github.com/spf13/cobra/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000ec000, 0x10, 0x0, 0x0)
	/skaffold/vendor/github.com/spf13/cobra/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/skaffold/vendor/github.com/spf13/cobra/command.go:887
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/skaffold/vendor/github.com/spf13/cobra/command.go:880
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app.Run(0x212b9e0, 0xc00012c000, 0x212b9e0, 0xc00012c008, 0x0, 0x0)
	/skaffold/cmd/skaffold/app/skaffold.go:47 +0x13d
main.main()
	/skaffold/cmd/skaffold/skaffold.go:35 +0x4e
drewpca-laptop(pts/1):~/Downloads/skaffold/examples/getting-started% 

```

**Comment by tejal29** [comment]
@drewpca makes sense. Skaffold should attempt to parse dockerfiles instructions before reading them. 
Definitely, something to look into for the team.

**Comment by tejal29** [comment]
Downgrading it to p3 as its not a priority right now
