### ISSUE TITLE
Deploying to EKS gives an error

### ISSUE THREAD

**Issue by devi-sandireddy** [GoogleContainerTools/skaffold#4786]
```
Starting deploy...
Helm release myapp not installed. Installing...
NAME: myapp
LAST DEPLOYED: Tue Sep 15 12:55:30 2020
NAMESPACE: test-app
STATUS: deployed
REVISION: 1
TEST SUITE: None
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy/kubectl.(*namespaceCollector).Visit(0xc0000100b0, 0xc00099c930, 0xc00064a578, 0x8, 0x57684c0, 0xc00099ca20, 0xc00064a501)
        /private/tmp/skaffold-20200903-47925-9prb4r/pkg/skaffold/deploy/kubectl/namespaces.go:61 +0x12c
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy/kubectl.visitFields(0x57684c0, 0xc00099c930, 0x5d24220, 0xc0000100b0)
        /private/tmp/skaffold-20200903-47925-9prb4r/pkg/skaffold/deploy/kubectl/visitor.go:133 +0x103
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy/kubectl.traverseManifestFields(0xc00099c930, 0x5d24220, 0xc0000100b0)
        /private/tmp/skaffold-20200903-47925-9prb4r/pkg/skaffold/deploy/kubectl/visitor.go:83 +0x65
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy/kubectl.(*ManifestList).Visit(0xc000d5a768, 0x5d24220, 0xc0000100b0, 0x40fbc59, 0xc00099f2c0, 0xc000941444, 0x3, 0x3)
        /private/tmp/skaffold-20200903-47925-9prb4r/pkg/skaffold/deploy/kubectl/visitor.go:65 +0x1e5
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy/kubectl.(*ManifestList).CollectNamespaces(0xc000d5a768, 0x104, 0x12d, 0xc000d5a75e, 0xa, 0xa)
        /private/tmp/skaffold-20200903-47925-9prb4r/pkg/skaffold/deploy/kubectl/namespaces.go:29 +0x90
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy.getObjectNamespaceIfDefined(0xc00067e000, 0x104, 0x12d, 0xc000834958, 0x8, 0x0, 0x5d23f40, 0xc000652f80, 0x0)
        /private/tmp/skaffold-20200903-47925-9prb4r/pkg/skaffold/deploy/util.go:95 +0x10d
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy.parseReleaseInfo(0xc000834958, 0x8, 0xc0009962a0, 0xc000941000, 0x3, 0x0)
        /private/tmp/skaffold-20200903-47925-9prb4r/pkg/skaffold/deploy/util.go:73 +0x1f2
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy.(*HelmDeployer).deployRelease(0xc0009000a0, 0x5d6d6e0, 0xc0005ea080, 0x5d27e40, 0xc000010018, 0xc000834950, 0x5, 0xc000535400, 0x11, 0xc0005eb380, ...)
        /private/tmp/skaffold-20200903-47925-9prb4r/pkg/skaffold/deploy/helm.go:406 +0x9db
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy.(*HelmDeployer).Deploy(0xc0009000a0, 0x5d6d6e0, 0xc0005ea080, 0x5d27e40, 0xc000010018, 0xc000cb0a00, 0x1, 0x1, 0x400f950, 0xc000cecb00, ...)
        /private/tmp/skaffold-20200903-47925-9prb4r/pkg/skaffold/deploy/helm.go:108 +0xb8d
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.withTimings.Deploy(0x5d35ba0, 0xc000724600, 0x5d3fca0, 0xc000514e60, 0x5d6d8e0, 0xc0009000a0, 0x1, 0x5d6d6e0, 0xc0005ea080, 0x5d27e40, ...)
        /private/tmp/skaffold-20200903-47925-9prb4r/pkg/skaffold/runner/timings.go:84 +0x142
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.(*SkaffoldRunner).Deploy(0xc000918000, 0x5d6d6e0, 0xc0005ea080, 0x5d27e40, 0xc000010018, 0xc000cb0a00, 0x1, 0x1, 0x1, 0x0)
        /private/tmp/skaffold-20200903-47925-9prb4r/pkg/skaffold/runner/deploy.go:75 +0x60d
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.(*SkaffoldRunner).DeployAndLog(0xc000918000, 0x5d6d6e0, 0xc0005ea080, 0x5d27e40, 0xc000010018, 0xc000cb0a00, 0x1, 0x1, 0x0, 0x0)
        /private/tmp/skaffold-20200903-47925-9prb4r/pkg/skaffold/runner/build_deploy.go:112 +0x1f6
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.doRun.func1(0x5d88040, 0xc000918000, 0xc0007a68c0, 0x0, 0x100000001)
        /private/tmp/skaffold-20200903-47925-9prb4r/cmd/skaffold/app/cmd/run.go:50 +0x1a9
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.withRunner(0x5d6d6e0, 0xc0005ea080, 0xc00087fbf8, 0xc00087fc20, 0x41fd525)
        /private/tmp/skaffold-20200903-47925-9prb4r/cmd/skaffold/app/cmd/runner.go:49 +0x13c
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.doRun(0x5d6d6e0, 0xc0005ea080, 0x5d27e40, 0xc000010018, 0xc000010018, 0xc0000f2100)
        /private/tmp/skaffold-20200903-47925-9prb4r/cmd/skaffold/app/cmd/run.go:44 +0x85
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.(*builder).NoArgs.func1(0xc0005aedc0, 0xc0005a9100, 0x0, 0x2, 0x0, 0x0)
        /private/tmp/skaffold-20200903-47925-9prb4r/cmd/skaffold/app/cmd/commands.go:111 +0x98
github.com/spf13/cobra.(*Command).execute(0xc0005aedc0, 0xc0005a90e0, 0x2, 0x2, 0xc0005aedc0, 0xc0005a90e0)
        /private/tmp/skaffold-20200903-47925-9prb4r/vendor/github.com/spf13/cobra/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0005aeb00, 0x10, 0x0, 0x0)
        /private/tmp/skaffold-20200903-47925-9prb4r/vendor/github.com/spf13/cobra/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /private/tmp/skaffold-20200903-47925-9prb4r/vendor/github.com/spf13/cobra/command.go:887
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /private/tmp/skaffold-20200903-47925-9prb4r/vendor/github.com/spf13/cobra/command.go:880
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app.Run(0x5d27e40, 0xc000010018, 0x5d27e40, 0xc000010020, 0x0, 0x0)
        /private/tmp/skaffold-20200903-47925-9prb4r/cmd/skaffold/app/skaffold.go:47 +0x13f
main.main()
        /private/tmp/skaffold-20200903-47925-9prb4r/cmd/skaffold/skaffold.go:35 +0x4e
```

Skaffold run or Skaffold deploy deploys the pods to EKS, but produces the following error

### Information

- Skaffold version: v1.14.0
- Operating system: mac or gitlab runner, same result
- Contents of skaffold.yaml:

```yaml
 apiVersion: skaffold/v2beta3
kind: Config
build:
  artifacts:
    - image:  hello-world
      context: .
      docker: 
        dockerfile: Dockerfile
      # jib: {}
  tagPolicy:
    sha256: {}
  
deploy:
  # statusCheckDeadlineSeconds: 300
  helm:
    releases:
    - name: myapp
      chartPath: charts/helloworld
      wait: true
      valuesFiles:
        - charts/helloworld/values.yaml
      namespace: test-app

```

### Steps to reproduce the behavior

1 skaffold run  ---default-repo XXX.dkr.ecr.us-east-1.amazonaws.com
3. skaffold deploy -a skaffold-build.jsaon

**Comment by tejal29** [comment]
@devi-sandireddy Can you please provide error logs?
