### ISSUE TITLE
Configs can't have same image but with different tags

### ISSUE THREAD

**Issue by braderhart** [GoogleContainerTools/skaffold#5603]
### Expected behavior
When using multiple configs, they should be able to share the same image but have different tags. When building Docker images this is common for building different versions of the same software.

### Information

- Skaffold version: v1.20.0
- Operating system: Arch Linux 5.11.9-arch1-1 x86_64
- Installed via: Arch Packages
- Contents of skaffold.yaml:

```yaml
.config: &config
  apiVersion: skaffold/v2beta12
  build: &build
    artifacts: &artifacts
    - context: &context docker/hugo
      docker: &docker
        buildArgs: &buildArgs
          CGO_ENABLED: 0
          GOFLAGS: -ldflags=-s -ldflags=-w
          HUGO_SHA256: f156c31034f013b11ff19aec09ab4d47fd8689befaa6f58222b48ed970722b4b
          HUGO_VERSION: 0.82.0
        noCache: &noCache true
      image: &image sample/hugo
    local:
      push: false
      useBuildkit: true
    tagPolicy:
      envTemplate:
        template: alpine
  kind: Config
  metadata:
    name: hugo

<<: *config

---

<<: *config
build:
  <<: *build
  artifacts:
  - context: *context
    docker:
      <<: *docker
      buildArgs:
        <<: *buildArgs
        GOFLAGS: -ldflags=-s -ldflags=-w -tags=nodeploy
      noCache: *noCache
    image: *image
  tagPolicy:
    envTemplate:
      template: nodeploy-alpine
metadata:
  name: hugo-nodeploy
```

### Steps to reproduce the behavior

1. Create a skaffold.yaml containing multiple configs sharing the image name, but with different tags
2. `skaffold build`

```
[+] Building 76.8s (10/10) FINISHED
 => [internal] load build definition from Dockerfile                                               0.0s
 => => transferring dockerfile: 38B                                                                0.0s
 => [internal] load .dockerignore                                                                  0.0s
 => => transferring context: 2B                                                                    0.0s
 => [internal] load metadata for docker.io/library/alpine:latest                                   0.0s
 => [internal] load metadata for docker.io/library/golang:alpine                                   0.0s
 => CACHED [build 1/2] FROM docker.io/library/golang:alpine                                        0.0s
 => CACHED [stage-1 1/3] FROM docker.io/library/alpine                                             0.0s
 => [build 2/2] RUN wget  --output-document "/hugo-v0.82.0.tar.gz"   "https://github.com/gohugoi  75.7s
 => [stage-1 2/3] COPY --from=build /go/bin/hugo /usr/local/bin/hugo                               0.1s
 => [stage-1 3/3] WORKDIR /data                                                                    0.2s
 => exporting to image                                                                             0.7s
 => => exporting layers                                                                            0.7s
 => => writing image sha256:f8ba6fb8b2cd85e7294e7f0b5071d26b51bfce6f63a3e83e198c9bc03bcf0ce2       0.0s
 => => naming to docker.io/sample/hugo:nodeploy-alpine                                            0.0s
panic: close of closed channel

goroutine 67 [running]:
github.com/GoogleContainerTools/skaffold/pkg/skaffold/build.(*node).markComplete(0xc000719e58)
	/build/skaffold/src/gopath/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/model.go:39 +0x38
github.com/GoogleContainerTools/skaffold/pkg/skaffold/build.(*scheduler).build(0xc0009c5c20, 0x55dbaffa0af0, 0xc000369ac0, 0xc0005594a0, 0x0, 0x0, 0x0)
	/build/skaffold/src/gopath/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/scheduler.go:105 +0x585
github.com/GoogleContainerTools/skaffold/pkg/skaffold/build.(*scheduler).run.func1(0x0, 0x0)
	/build/skaffold/src/gopath/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/scheduler.go:65 +0x91
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0006c9110, 0xc0006c9140)
	/build/skaffold/src/gopath/pkg/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57 +0x87
created by golang.org/x/sync/errgroup.(*Group).Go
	/build/skaffold/src/gopath/pkg/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:54 +0x71
```

**Comment by nkubala** [comment]
related: https://github.com/GoogleContainerTools/skaffold/issues/1269 and https://github.com/GoogleContainerTools/skaffold/issues/2169

**Comment by tejal29** [comment]
Thanks @nkubala
