### ISSUE TITLE
`%!s(<nil>)\n` printed at termination of dev session

### ISSUE THREAD

**Issue by etanshaul** [GoogleContainerTools/skaffold#6747]
To repro:

Using CC managed Skaffold version: `v1.32.0`

1) run the Cloud Code go hello-world sample (or really any app) in CC IJ
2) let the session complete
3) Click the stop button

Expected:
Normal skaffold cleanup messages only

Actual:
We do get the normal cleanup messages, but afterwards a `%!s(<nil>)` is printed:
<img width="1093" alt="Screen Shot 2021-10-19 at 11 06 36 AM" src="https://user-images.githubusercontent.com/1735744/137938499-40f86190-1f48-47d7-bb8a-ad68b1fa1b98.png">

The event from the API looks as follows:
```
skaffoldLogEvent {
  task_id: "DevLoop-1"
  subtask_id: "-1"
  level: STANDARD
  message: "%!s(<nil>)\n"
}
```

**Comment by briandealwis** [comment]
Fun!  This message is sent along in a `skaffoldLogEvent` and doesn't show up on the terminal:
```json
{
  "result": {
    "timestamp": "2021-12-06T21:37:55.332988Z",
    "skaffoldLogEvent": {
      "task_id": "DevLoop-1",
      "subtask_id": "-1",
      "level": "STANDARD",
      "message": "%!s(<nil>)\n"
    }
  }
}
```

<details>
<summary>details finding the problem</summary>

I ended up having to run with the following diff to see what was happening:
```diff
--- pkg/skaffold/event/v2/logger.go
+++ pkg/skaffold/event/v2/logger.go
@@ -51,6 +51,9 @@ func (l logger) Write(p []byte) (int, error) {
 }
 
 func (ev *eventHandler) handleSkaffoldLogEvent(e *proto.SkaffoldLogEvent) {
+       if e.Message == "%!s(\u003cnil\u003e)\n" {
+               panic(e.Message)
+       }
```

It only happens once the app has passed the status checks:

```
panic: %!s(<nil>)

goroutine 1 [running]:
github.com/GoogleContainerTools/skaffold/pkg/skaffold/event/v2.(*eventHandler).handleSkaffoldLogEvent(0x140001c0e40, 0x140014d4900)
	/Users/bdealwis/Projects/Skaffold/repo-skaffold/pkg/skaffold/event/v2/logger.go:55 +0x340
github.com/GoogleContainerTools/skaffold/pkg/skaffold/event/v2.(*eventHandler).sendErrorMessage.func1()
	/Users/bdealwis/Projects/Skaffold/repo-skaffold/pkg/skaffold/event/v2/event.go:214 +0x368
sync.(*Once).doSlow(0x140001c0e98, 0x140013b5528)
	/Users/bdealwis/installs/go-1.17.2/src/sync/once.go:68 +0xe0
sync.(*Once).Do(0x140001c0e98, 0x140013b5528)
	/Users/bdealwis/installs/go-1.17.2/src/sync/once.go:59 +0x4c
github.com/GoogleContainerTools/skaffold/pkg/skaffold/event/v2.(*eventHandler).sendErrorMessage(0x140001c0e40, {0x106e0e76b, 0x7}, {0x106e09666, 0x2}, {0x0, 0x0})
	/Users/bdealwis/Projects/Skaffold/repo-skaffold/pkg/skaffold/event/v2/event.go:213 +0xf4
github.com/GoogleContainerTools/skaffold/pkg/skaffold/event/v2.SendErrorMessageOnce({0x106e0e76b, 0x7}, {0x106e09666, 0x2}, {0x0, 0x0})
	/Users/bdealwis/Projects/Skaffold/repo-skaffold/pkg/skaffold/event/v2/event.go:209 +0x60
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.apiServerShutdownHook({0x0, 0x0})
	/Users/bdealwis/Projects/Skaffold/repo-skaffold/cmd/skaffold/app/cmd/cmd.go:322 +0x70
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.applyPostRunHooks.func1(0x140005c22c0, {0x140001c0f00, 0x0, 0xc})
	/Users/bdealwis/Projects/Skaffold/repo-skaffold/cmd/skaffold/app/cmd/commands.go:185 +0x80
github.com/spf13/cobra.(*Command).execute(0x140005c22c0, {0x140001c0540, 0xc, 0xc})
	/Users/bdealwis/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x998
github.com/spf13/cobra.(*Command).ExecuteC(0x140005c0000)
	/Users/bdealwis/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x7b8
github.com/spf13/cobra.(*Command).ExecuteContextC(0x140005c0000, {0x10790dd90, 0x140009ac080})
	/Users/bdealwis/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:911 +0x74
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app.Run({0x1078c76c0, 0x14000126008}, {0x1078c76c0, 0x14000126010})
	/Users/bdealwis/Projects/Skaffold/repo-skaffold/cmd/skaffold/app/skaffold.go:50 +0x3e4
main.main()
	/Users/bdealwis/Projects/Skaffold/repo-skaffold/cmd/skaffold/skaffold.go:49 +0x29c
```

</details>

It happens because of the [`apiServerShutdownHook` post-run hook](https://github.com/GoogleContainerTools/skaffold/blob/main/cmd/skaffold/app/cmd/commands.go#L130) which is called with the error object from running the cobra `Cmd` object.  This object is `nil` when the app is interrupted via <kbd>Ctrl</kbd><kbd>C</kbd> or stopped within the IDE.  And so `nil` error gets passed into a printf on line 217:
https://github.com/GoogleContainerTools/skaffold/blob/ef6c83e2737a974ba6d13789a6e2a230c0614b76/pkg/skaffold/event/v2/event.go#L212-L221

THis was brought in with #6516.  @MarlonGamez do you think we should just skip the event send if the error is `nil`?

**Comment by MarlonGamez** [comment]
@briandealwis that seems like the best thing to do. I can open a PR to fix this
