### ISSUE TITLE
skaffold build can give interface conversion error when Pod succeeded check fails

### ISSUE THREAD

**Issue by JasonCrease** [GoogleContainerTools/skaffold#6859]
### Behavior
When we execute ``skaffold build`` we occasionally get the error:
`panic: interface conversion: runtime.Object is *v1.Status, not *v1.Pod`
This particularly happens when we're having networking issues, or other cluster stability issues.

### Analysis
The type-assertion here seems to be the issue:
https://github.com/GoogleContainerTools/skaffold/blob/main/pkg/skaffold/kubernetes/wait.go#L78
If the request errors, the the type will be Status, rather than Pod. See:
https://github.com/kubernetes/apimachinery/blob/master/pkg/watch/watch.go#L57

### Log
```
 panic: interface conversion: runtime.Object is *v1.Status, not *v1.Pod
   
   goroutine 150 [running]:   github.com/GoogleContainerTools/skaffold/pkg/skaffold/kubernetes.isPodSucceeded.func1(0xc000f8ef20, 0xc000f8ef20, 0x2, 0x1)
     /skaffold/pkg/skaffold/kubernetes/wait.go:77 +0x287   
   github.com/GoogleContainerTools/skaffold/pkg/skaffold/kubernetes.watchUntilTimeout(0x260efe0, 0xc00096a3c0, 0x1176592e000, 0x25d2ea0, 0xc0009a8ec0, 0xc000f8e100, 0x0, 0x0)
     /skaffold/pkg/skaffold/kubernetes/wait.go:48 +0x1e8
   github.com/GoogleContainerTools/skaffold/pkg/skaffold/kubernetes.WaitForPodSucceeded(0x260ef60, 0xc000cbbf80, 0x263e760, 0xc0009db260, 0xc000a1c424, 0xc, 0x1176592e000, 0x0, 0x0)
     /skaffold/pkg/skaffold/kubernetes/wait.go:69 +0x296
   github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/cluster.(*Builder).buildWithKaniko(0xc00096aea0, 0x260ef60, 0xc000cbbf80, 0x25b7d40, 0xc00000f950, 0xc0000d4e70, 0x23, 0xc00068a5f0, 0x47, 0xc0002b78c0, ...)
     /skaffold/pkg/skaffold/build/cluster/kaniko.go:87 +0x943
   github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/cluster.(*Builder).runBuildForArtifact(0xc00096aea0, 0x260ef60, 0xc000cbbf80, 0x25b7d40, 0xc00000f950, 0xc0004c90a0, 0xc000e5c000, 0x58, 0x0, 0x219992c, ...)
     /skaffold/pkg/skaffold/build/cluster/cluster.go:82 +0x5cb
   github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/cluster.(*Builder).buildArtifact(0xc00096aea0, 0x260ef60, 0xc000cbbf80, 0x25b7d40, 0xc00000f950, 0xc0004c90a0, 0xc000e5c000, 0x58, 0x0, 0x0, ...)
     /skaffold/pkg/skaffold/build/cluster/cluster.go:65 +0x87
   github.com/GoogleContainerTools/skaffold/pkg/skaffold/build.(*BuilderMux).Build.func1(0x260ef60, 0xc000cbbf80, 0x25b7d40, 0xc00000f950, 0xc0004c90a0, 0xc000e5c000, 0x58, 0x1, 0xc0005e2b40, 0xc0005e2ae0, ...)
     /skaffold/pkg/skaffold/build/builder_mux.go:96 +0x100
   github.com/GoogleContainerTools/skaffold/pkg/skaffold/build.performBuild(0x260ef60, 0xc000cbbf80, 0x25b7d40, 0xc00000f950, 0xc000c023f0, 0xc0004c90a0, 0xc000eb21b0, 0xc000b01b88, 0xc000b01c38, 0xc000b0ff68, ...)
     /skaffold/pkg/skaffold/build/scheduler.go:132 +0x158
   github.com/GoogleContainerTools/skaffold/pkg/skaffold/build.(*scheduler).build(0xc000c66180, 0x260ef60, 0xc000cbbf80, 0xc000c023f0, 0x0, 0x0, 0x0)
     /skaffold/pkg/skaffold/build/scheduler.go:99 +0x439
   github.com/GoogleContainerTools/skaffold/pkg/skaffold/build.(*scheduler).run.func1(0x1, 0x0)
     /skaffold/pkg/skaffold/build/scheduler.go:66 +0x4e
   golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000eb4270, 0xc000eb42a0)
     /go/pkg/mod/golang.org/x/sync@v0.0.0-20201207232520-09787c993a3a/errgroup/errgroup.go:57 +0x59
```

**Comment by JasonCrease** [comment]
Thanks! Impressively quick fix!
