### ISSUE TITLE
[CI/CD Flake] - panic: Log in goroutine after TestDevSync/inferred_sync_with_notify_trigger has completed:

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#7639]
Github Actions full log:
https://github.com/GoogleContainerTools/skaffold/runs/7292465659?check_suite_focus=true

Relevant snippet:
```
panic: Log in goroutine after TestDevSync/inferred_sync_with_notify_trigger has completed: Ran [skaffold dev --namespace skaffold2cfw5 -f skaffold-infer.yaml --default-repo gcr.io/k8s-skaffold --trigger notify] in 5.799 seconds
goroutine 632 [running]:
testing.(*common).logDepth(0xc000120b60, {0xc0000f8360, 0x88}, 0x3)
	/opt/hostedtoolcache/go/1.17.11/x64/src/testing/testing.go:779 +0x4c9
testing.(*common).log(...)
	/opt/hostedtoolcache/go/1.17.11/x64/src/testing/testing.go:761
testing.(*common).Logf(0xc0009349d0, {0x28362a5, 0xa}, {0xc0013187b0, 0xc0013187a8, 0x1})
	/opt/hostedtoolcache/go/1.17.11/x64/src/testing/testing.go:807 +0x4c
github.com/GoogleContainerTools/skaffold/integration/skaffold.(*RunBuilder).runForked.func1()
	/home/runner/work/skaffold/skaffold/integration/skaffold/helper.go:245 +0x105
created by github.com/GoogleContainerTools/skaffold/integration/skaffold.(*RunBuilder).runForked
	/home/runner/work/skaffold/skaffold/integration/skaffold/helper.go:243 +0x2c5
FAIL	github.com/GoogleContainerTools/skaffold/integration	460.020s
```

**Comment by aaron-prindle** [comment]
Haven't seen this for a while, marking closed (fixed)
